config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flat_path(@flat)
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path
  end

  def edit
     @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)
    redirect_to flats_path
  end

  private

    def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit "edit a flat", class: "btn btn-primary" %>

<% end %>

app/views/flats/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Simple Airbnb</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  <form class="form-inline my-2 my-lg-0 method="get" action="flats/new">
   <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Add Flat</button>
</form>
</nav>

<h1>All our flats(6)</h1>


    <div class="d-flex">
      <% @flats.each do |flat| %>
        <div class="d-flex justify-content-between">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
                    <%= flat[:name] %> (<%= flat[:address] %>)
                     <p><%= flat[:description] %></p>
                      <p><%= flat[:price_per_night] %> <i class="fas fa-euro-sign"></i>
                       <%= flat[:number_of_guests] %> <i class="fas fa-users"></i></p>
                      <%= link_to "Commentaires", flat_path(flat) %>
                      <%= link_to "Supprimer", flat_path(flat),
                        method: :delete,
                        data: { confirm: "Etes vous sur de vouloir supprimer cet appartement?" } %>
                      <%= link_to "Editer", edit_flat_path(flat) %>
            </li>
              <% end %>
          </ul>
       </div>
    </div>

app/views/flats/new.html.erb
<!-- <form action="/flats" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="name" placeholder="Name">
  <input type="text" name="address" placeholder="Address">
  <input type="text" name="description" placeholder="Description">
  <input type="text" name="price_per_night" placeholder="Price per night">
  <input type="text" name="number_of_guests" placeholder="Number of guests">
  <input type="submit">
</form> -->
<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit "add a flat", class: "btn btn-primary" %>
<% end %>

app/views/flats/show.html.erb
<%= @flat.description%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <script src="https://kit.fontawesome.com/fd6fac02f6.js" crossorigin="anonymous"></script>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>